version: '3'

services:
  database-local:
    image: mysql:5.7
    hostname: local-database
    container_name: local-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    ports:
      - "3306:3306"
    volumes:
      - ./initialise_mysql.sql:/docker-entrypoint-initdb.d/initialise_mysql.sql
      # - ./data:/var/lib/mysql
    command:
      # - --default-time-zone=Asia/Seoul
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=0

# docker compose -p cart up -d
